CREATE SCHEMA brh;
USE brh;

CREATE TABLE ENDERECO (
    CEP VARCHAR(15) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL, 
    CIDADE VARCHAR(100) NOT NULL, 
    ESTADO VARCHAR(100) NOT NULL, 
    CONSTRAINT PK_CEP PRIMARY KEY (CEP)
);


CREATE TABLE PESSOA (
    CPF VARCHAR (20) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL_PESSOAL VARCHAR(100) NOT NULL,
    CEP VARCHAR(15) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    FOREIGN KEY (CEP) REFERENCES ENDERECO (CEP) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE DEPARTAMENTO (
	SIGLA VARCHAR(100) NOT NULL,
    NOME VARCHAR (100) NOT NULL,
    CHEFE VARCHAR(100) NOT NULL,
    DEPARTAMENTO_SUPERIOR VARCHAR(100) NOT NULL,    
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (SIGLA)
);

CREATE TABLE COLABORADOR (
    MATRICULA VARCHAR (100) NOT NULL PRIMARY KEY,
    CPF VARCHAR (20) NOT NULL,
    EMAIL_CORPORATIVO VARCHAR(100) NOT NULL, 
    SALARIO DECIMAL (7,2) NOT NULL,
    DEPARTAMENTO VARCHAR(100) NOT NULL,
    FOREIGN KEY (CPF) REFERENCES PESSOA (CPF) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
	FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (SIGLA) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE DEPENDENTE (
	CPF_DEPENDENTE VARCHAR (20) NOT NULL PRIMARY KEY,
    COLABORADOR VARCHAR (100) NOT NULL,
    NOME_DEPENDENTE VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    PARENTESCO VARCHAR(100) NOT NULL,
    FOREIGN KEY (COLABORADOR) REFERENCES COLABORADOR (MATRICULA) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE	
);


CREATE TABLE PROJETO (
	PROJETO_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    NOME_PROJETO VARCHAR (100) NOT NULL,
    RESPONSAVEL VARCHAR(100) NOT NULL,
    INICIO DATE NOT NULL,  
    FIM DATE NOT NULL,
    FOREIGN KEY (RESPONSAVEL) REFERENCES COLABORADOR (MATRICULA) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE PAPEL (
	PAPEL_ID VARCHAR(100) NOT NULL,
    NOME VARCHAR (100) NOT NULL,
    PRIMARY KEY (PAPEL_ID)
);

CREATE TABLE ATRIBUICAO (
	COLABORADOR_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    PROJETO_ID VARCHAR (100) NOT NULL,
    PAPEL_ID VARCHAR(100) NOT NULL,
    FOREIGN KEY (COLABORADOR_ID) REFERENCES COLABORADOR (MATRICULA) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
	FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (PROJETO_ID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
    FOREIGN KEY (COLABORADOR_ID) REFERENCES COLABORADOR (MATRICULA) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
	FOREIGN KEY (PAPEL_ID) REFERENCES PAPEL (PAPEL_ID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);


CREATE TABLE TELEFONE (
	TELEFONE VARCHAR(30) NOT NULL PRIMARY KEY,
    MATRICULA VARCHAR(100) NOT NULL,
    FOREIGN KEY (MATRICULA) REFERENCES COLABORADOR (MATRICULA) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);




